# Site Info
title: 안녕지구
tagline: '#developer #bompapa'
description: '안녕하세요. 공부하는 개발자입니다.'
baseurl: ""
url: http://hijigoo.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: 안녕지구
  description: 안녕하세요. 기록하는 개발자입니다.
  # gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/HiJiGOO
    # facebook:  <hide>
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:     mailto:hi.jigoo@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Categories: 
    - '/blog/categories/'
    - { Algorithm: '/blog/categories/#algorithm' }
    - { Architecture: '/blog/categories/#architecture' }
    - { Clean Code: '/blog/categories/#clean-code' }
    - { Design Pattern: '/blog/categories/#design-pattern' }
    - { Bixby: '/blog/categories/#bixby' }
    - { NLP: '/blog/categories/#nlp' }
    - { Reinforcement Learning: '/blog/categories/#reinforcement-learning' }
    - { Flutter: '/blog/categories/#flutter' }
    - { Daily: '/blog/categories/#daily' }
    
  Tags:
    - '/blog/tags/'
  # Blog:           
  #   - '/blog/'
  #   - { Categories: '/blog/categories/' }
  #   - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  # Github Project: 
  #   - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/bom_family.jpg
  caption: <b>Bom</b>'s <i>Family</i>
  # image: /public/img/we_will_be_giants_by_yalestewart.jpg
  # caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-130716162-1' # leave blank if you don't want google analytics
disqus_short_name: 'hijigoo' # leave blank if you don't want disqus

# Highlighter
# highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
